### ISSUE TITLE
Fortran and i686 support

### ISSUE THREAD

**Issue by alanliska** [mvaisakh/gcc-build#23]
Hello,
could it be possible to
(a) add Fortran support (--languages=c,c++,fortran) to your toolchains
and 
(b) create similar cross-compiler set (arm-gcc, aarch64-gcc, x86_64-gcc) also for x86?
I tried to do it myself but unfortunately, I did not succeed even with the pre-set configuration in your script (using WSL Ubuntu)... either one of the downoad mirrors is unavailable from my place, or the compilation crashes elsewhere. 
Thanks,
AL

**Comment by mvaisakh** [comment]
Hi,
I used to build x86_64 gcc, but it seemed like nobody used it, hence I discontinued it for CI builds. For fortran support, I'll push a change.

**Comment by mvaisakh** [comment]
Fortran support has been added with commit 182d30fa8a70465e7a6b82745ab6dc9493367b77

**Comment by alanliska** [comment]
Many thanks!
