### ISSUE TITLE
 internal compiler error: in related_int_vector_mode, at stor-layout.cc:581

### ISSUE THREAD

**Issue by TogoFire** [mvaisakh/gcc-build#30]
during GIMPLE pass: vect
../techpack/camera/drivers/cam_isp/isp_hw_mgr/isp_hw/ife_csid_hw/cam_ife_csid_core.c: In function 'cam_ife_csid_process_cmd':
../techpack/camera/drivers/cam_isp/isp_hw_mgr/isp_hw/ife_csid_hw/cam_ife_csid_core.c:4597:12: internal compiler error: in related_int_vector_mode, at stor-layout.cc:581
 4597 | static int cam_ife_csid_process_cmd(void *hw_priv,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~
  CC      techpack/dataipa/drivers/platform/msm/ipa/ipa_v3/ipa_uc.o
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://gcc.gnu.org/bugs/> for instructions.
  CC      drivers/clk/qcom/clk-opp.o
make[4]: *** [../scripts/Makefile.build:287: techpack/camera/drivers/cam_isp/isp_hw_mgr/isp_hw/ife_csid_hw/cam_ife_csid_core.o] Error 1

during GIMPLE pass: vect
../kernel/sched/psi.c: In function 'collect_percpu_times.constprop':
../kernel/sched/psi.c:312:13: internal compiler error: in related_int_vector_mode, at stor-layout.cc:581
  312 | static void collect_percpu_times(struct psi_group *group,
      |             ^~~~~~~~~~~~~~~~~~~~
  CC      drivers/crypto/msm/qcedev.o
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://gcc.gnu.org/bugs/> for instructions.
  CC      drivers/clk/qcom/clk-regmap-mux-div.o
make[3]: *** [../scripts/Makefile.build:287: kernel/sched/psi.o] Error 1

during GIMPLE pass: vect
../fs/proc/array.c: In function 'proc_pid_status':
../fs/proc/array.c:404:5: internal compiler error: in related_int_vector_mode, at stor-layout.cc:581
  404 | int proc_pid_status(struct seq_file *m, struct pid_namespace *ns,
      |     ^~~~~~~~~~~~~~~
  CC      techpack/dataipa/drivers/platform/msm/ipa/ipa_v3/ipa_wdi3_i.o
  CC      lib/zstd/compress/zstd_fast.o
  AR      sound/usb/bcd2000/built-in.a
  AR      drivers/dax/pmem/built-in.a
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://gcc.gnu.org/bugs/> for instructions.
  CC      techpack/display/msm/dp/dp_pll_5nm.o
  CC      mm/madvise.o
  CC      drivers/dax/super.o
  AR      sound/usb/caiaq/built-in.a
make[3]: *** [../scripts/Makefile.build:287: fs/proc/array.o] Error 1

during GIMPLE pass: vect
../lib/zstd/decompress/huf_decompress.c: In function 'HUF_readDTableX1_wksp':
../lib/zstd/decompress/huf_decompress.c:354:8: internal compiler error: in related_int_vector_mode, at stor-layout.cc:581
  354 | size_t HUF_readDTableX1_wksp(HUF_DTable* DTable, const void* src, size_t srcSize, void* workSpace, size_t wkspSize, int flags)
      |        ^~~~~~~~~~~~~~~~~~~~~
  CC      sound/usb/validate.o
  CC      sound/usb/media.o
  CC      net/ipv6/icmp.o
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://gcc.gnu.org/bugs/> for instructions.
make[3]: *** [../scripts/Makefile.build:287: lib/zstd/decompress/huf_decompress.o] Error 1

during GIMPLE pass: vect
../drivers/net/wireless/cnss2/qmi.c: In function 'cnss_wlfw_request_mem_ind_cb':
../drivers/net/wireless/cnss2/qmi.c:2402:13: internal compiler error: in related_int_vector_mode, at stor-layout.cc:581
 2402 | static void cnss_wlfw_request_mem_ind_cb(struct qmi_handle *qmi_wlfw,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC      drivers/opp/cpu.o
  AR      drivers/media/usb/gspca/built-in.a
  CC      drivers/opp/of.o
In file included from ../techpack/display/msm/dsi/dsi_defs.h:12,
                 from ../techpack/display/msm/dsi/dsi_ctrl_hw.h:15,
                 from ../techpack/display/msm/dsi/dsi_ctrl_hw_2_2.c:7:
../techpack/display/msm/msm_drv.h:269:20: warning: 'msm_spr_pack_type_str' defined but not used [-Wunused-variable]
  269 | static const char *msm_spr_pack_type_str[MSM_DISPLAY_SPR_TYPE_MAX] = {
      |                    ^~~~~~~~~~~~~~~~~~~~~
  CC      drivers/pci/controller/pci-host-common.o
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://gcc.gnu.org/bugs/> for instructions.
  AR      drivers/media/usb/siano/built-in.a
make[5]: *** [../scripts/Makefile.build:287: drivers/net/wireless/cnss2/qmi.o] Error 1

during GIMPLE pass: vect
../drivers/net/wireless/ath/ath9k/calib.c: In function 'ath9k_hw_getnf':
../drivers/net/wireless/ath/ath9k/calib.c:400:6: internal compiler error: in related_int_vector_mode, at stor-layout.cc:581
  400 | bool ath9k_hw_getnf(struct ath_hw *ah, struct ath9k_channel *chan)
      |      ^~~~~~~~~~~~~~
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://gcc.gnu.org/bugs/> for instructions.
make[6]: *** [../scripts/Makefile.build:287: drivers/net/wireless/ath/ath9k/calib.o] Error 1

during GIMPLE pass: vect
../drivers/net/wireless/ath/carl9170/rx.c: In function '__carl9170_rx':
../drivers/net/wireless/ath/carl9170/rx.c:854:13: internal compiler error: in related_int_vector_mode, at stor-layout.cc:581
  854 | static void __carl9170_rx(struct ar9170 *ar, u8 *buf, unsigned int len)
      |             ^~~~~~~~~~~~~
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://gcc.gnu.org/bugs/> for instructions.
  CC      drivers/regulator/dummy.o
make[6]: *** [../scripts/Makefile.build:287: drivers/net/wireless/ath/carl9170/rx.o] Error 1

Gcc Eva version: 25072024.
https://bin.cyberknight777.dev/kdRJ/raw
kt: https://github.com/dev-sm8350/kernel_oneplus_sm8350

~$ gcc --version
gcc (GCC) 14.1.1 20240701 (Red Hat 14.1.1-7)
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

~$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="40 (Toolbx Container Image)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Toolbx Container Image)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Toolbx Container Image"
VARIANT_ID=toolbx

~$ ldd --version
ldd (GNU libc) 2.39
Copyright (C) 2024 Free Software Foundation, Inc.

**Comment by mvaisakh** [comment]
Hi try with today's build.

**Comment by TogoFire** [comment]
> Hi try with today's build.

![Screenshot_20240728-103443_JuiceSSH_1](https://github.com/user-attachments/assets/aa60a630-f897-4037-852f-c893cd4f914d)

Built perfectly, thank you. ❤️
