### ISSUE TITLE
ld.lld: error: undefined symbol: __popcountdi2

### ISSUE THREAD

**Issue by TogoFire** [mvaisakh/gcc-build#31]
Log:
ld.lld: error: undefined symbol: __popcountdi2
>>> referenced by msm_vidc_common.c
>>>               video/msm/vidc/msm_vidc_common.o:(msm_comm_set_color_format_constraints) in archive techpack/built-in.a
>>> referenced by dp_link.c
>>>               display/msm/dp/dp_link.o:(dp_link_process_request) in archive techpack/built-in.a
make[1]: *** [/home/togo77/kernel_oneplus_sm8350/Makefile:1299: vmlinux] Error 1
make: *** [Makefile:192: sub-make] Error 2

Full log:
https://bin.cyberknight777.dev/eVQ6/raw

kt: https://github.com/dev-sm8350/kernel_oneplus_sm8350
gcc used: 29082024
gcc of the day: 22082024. It was ok

**Comment by mvaisakh** [comment]
This doesn't look like gcc/LLD issue. Try compiling the same kernel source with an older version of gcc.
Does the same source build fine with the mentioned older gcc? Or was it building fine on that particular day?

**Comment by TogoFire** [comment]
> This doesn't look like gcc/LLD issue. Try compiling the same kernel source with an older version of gcc. Does the same source build fine with the mentioned older gcc? Or was it building fine on that particular day?

Old gcc compiles normally. Only this newer gcc one doesn't compile.

**Comment by mvaisakh** [comment]
I'll trigger a build now, check with that. Build will take approximately 6hours.

**Comment by TogoFire** [comment]
> I'll trigger a build now, check with that. Build will take approximately 6hours.

Unfortunately the error persists.

![IMG_20240830_063746_209](https://github.com/user-attachments/assets/d71d3a62-4510-4da7-995f-17b9f463e272)

gcc version: 30082024

**Comment by mvaisakh** [comment]
It seems like lld specific issue. Try switching from LLD to LD and see if that works.

**Comment by TogoFire** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/4d47534e-22ee-4689-9e0f-170a4022854c)
I don't think so. I'm using Fedora. With all dependencies installed.
sudo dnf install llvm gcc android-tools autoconf213 bison bzip2 ccache clang curl xmlstarlet bsdtar flex gawk gcc-c++ git git-lfs glibc-devel glibc-static libstdc++-static libX11-devel make mesa-libGL-devel ncurses-devel openssl patch zlib-devel ncurses-devel.i686 readline-devel.i686 libX11-devel.i686 mesa-libGL-devel.i686 glibc-devel.i686 libstdc++.i686 libXrandr.i686 zip perl-Digest-SHA python2 python3 wget lzop openssl-devel java-1.8.0-openjdk-devel ImageMagick ncurses schedtool lzip vboot-utils vim sha megatools aria2 libxcrypt-compat zram
sudo dnf groupinstall "Development Tools" "Development Libraries"

GCC version: 22082024 - (Build this version without any problems).
wget https://github.com/mvaisakh/gcc-build/releases/download/22082024/eva-gcc-arm-22082024.xz -O eva-gcc-arm.xz
wget https://github.com/mvaisakh/gcc-build/releases/download/22082024/eva-gcc-arm64-22082024.xz -O eva-gcc-arm64.xz
mkdir gcc-arm gcc-arm64
tar xvf eva-gcc-arm.xz
tar xvf eva-gcc-arm64.xz
![image](https://github.com/user-attachments/assets/76dc9491-754e-46f4-ad0b-8fad9df85e52)

GCC version 30082024 (RIP):
![image](https://github.com/user-attachments/assets/9b88f82a-eff7-4eaa-b324-eb150e83578a)

**Comment by mvaisakh** [comment]
No it has nothing to do with your system. You're using lld instead of gnu ld. Try using the gnu ld itself.

**Comment by TogoFire** [comment]
I just tried. It didn't work. It gives the same error.
I tried like this:
"HOSTLD=ld.lld" to "HOSTLD=ld" in script compile.sh
And then I tried removing HOSTLD. And the error persists.
![image](https://github.com/user-attachments/assets/23a3cb0c-fd95-438b-adae-626dd471672f)

**Comment by mvaisakh** [comment]
It's not HOSTLD, your kernel cross compiler ld differs. Drop the flag for using LLD with GCC and just use the regular GNU ld.

**Comment by TogoFire** [comment]
> It's not HOSTLD, your kernel cross compiler ld differs. Drop the flag for using LLD with GCC and just use the regular GNU ld.

In this case you are referring to removing the llvm flags to be able to use LD= $(CROSS_COMPILE)ld - From the kernel makefile. Is that it? If so. I removed the "LLVM_IAS=1" "LLVM=1" flags. And the error continues.
![image](https://github.com/user-attachments/assets/930dfcee-3bce-4acd-9f86-48c6ff9bd1da)
I'm sorry if I don't understand or am a bit lost.

**Comment by mvaisakh** [comment]
Hmm so it does look like a GCC side issue. I think you might need a kernel backport for this. For now you can stick to using older GCC.

**Comment by TogoFire** [comment]
> Hmm so it does look like a GCC side issue. I think you might need a kernel backport for this. For now you can stick to using older GCC.

Ok now.

![image](https://github.com/user-attachments/assets/1fbbfe17-3ae6-4152-b241-b8a9c9994f87)
![image](https://github.com/user-attachments/assets/3076fdfa-981a-4338-82d9-f79e4943e75b)
